version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: mbtidb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data # データ永続化のためのボリュームマウント
